### ISSUE TITLE
Acrescentar gráficos ao longo do tempo

### ISSUE THREAD

**Issue by heltonbiker** [gabrielcesar/covid-br#1]
Um dos aspectos importantes é visualizar a característica exponencial (se está aumentando ou diminuindo), e também a evolução dessa TAXA de aumento.

Veja aqui uma motivação pra isso:
https://www.youtube.com/watch?v=Kas0tIxDvrg

**Comment by gabrielcesar** [comment]
Muito bom @heltonbiker . Excelente contribuição. Vou estudar uma maneira de desenvolver esta funcionalidade. Obrigado pelo feedback.

**Comment by heltonbiker** [comment]
Aqui tem uns gráficos interessantes, em especial o gráfico LOGARÍTMICO dos casos, assim como uma explicação sobre o fator de crescimento, que me parece importante como "noção de andamento" da epidemia (se está crescendo ou passando)

https://www.worldometers.info/coronavirus/coronavirus-death-toll/

**Comment by gabrielcesar** [comment]
O gráfico de evolução da Pandemia foi adicionado. Obrigado pela sugestão.   

![COVID](https://raw.githubusercontent.com/gabrielcesar/covid-br/master/images/covid.png)
