### ISSUE TITLE
Ordenar as listas dos estados por número de casos ao invés de ordem alfabética

### ISSUE THREAD

**Issue by heltonbiker** [gabrielcesar/covid-br#2]
Primeira coisa é saber se você acha isso uma boa ideia.

Caso positivo, se gostaria que eu tentasse fazer um pull request

**Comment by gabrielcesar** [comment]
Sim, @heltonbiker isto é uma ótima ideia. ;)

**Comment by gabrielcesar** [comment]
Excelente @heltonbiker, ficou muito bom. Parabéns. Atualizei o README.
