### ISSUE TITLE
Número de casos não aparece quando o nome do estado é muito longo

### ISSUE THREAD

**Issue by heltonbiker** [gabrielcesar/covid-br#4]
Quando o número de casos tem três dígitos, estados com nome longo (Mato Grosso do Sul e Rio Grande do Norte) não exibem o número.

**Comment by gabrielcesar** [comment]
Olá Helton, eu diminui um pouco a fonte na Coluna da Esquerda, acredito que agora pode estar normal. Se você puder enviar um Screenshot, fica melhor para darmos uma olhadinha. Desde já, obrigado pelo Feedback.
