### ISSUE TITLE
Colunas redundantes - e distantes uma da outra - na exibição dos casos por estado

### ISSUE THREAD

**Issue by heltonbiker** [gabrielcesar/covid-br#6]
Sugestão seria ter uma única tabela com duas colunas, opcionalmente ordenável, em que se exibem os casos confirmados e a mortes lado a lado.

**Comment by gabrielcesar** [comment]
Muito boa sugestão, eu realinhei o Layout do Dashboard e coloquei os dados lado a lado, na mesma coluna.
