### ISSUE TITLE
Distribuição/Licença 

### ISSUE THREAD

**Issue by AppsCDN** [gabrielcesar/covid-br#7]
Oi, posso modificar os projetos do covid br e o do covid internacional e inseri como parte do conteúdo de um aplicativo que estou desenvolvendo? Se possível você poderia licenciar com a licença MIT. Darei créditos na área de créditos do app.

**Comment by gabrielcesar** [comment]
@EduSFreitas Olá. Pode sim. Obrigado. ;)

**Comment by AppsCDN** [comment]
Eu que agradeço! obrigado 👍
